/*
 * Display game event log. 
 */
package soen6441.team13.wars.presentation;

import soen6441.team13.wars.domain.Action;
import soen6441.team13.wars.logger.ActionLogger;
import ca.odell.glazedlists.EventList;
import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.gui.TableFormat;
import ca.odell.glazedlists.swing.EventTableModel;
import ca.odell.glazedlists.swing.GlazedListsSwing;

/**
 * Panel that display game events.
 */
public class LogPanel extends javax.swing.JPanel {
	private static final long serialVersionUID = 1L;

	private EventList<Action> eventList;
	private final boolean[] editable = { false, false, false, false };
	private final String[] propertyNames = new String[] { "order", "player", "action", "result" };

	/** Creates new form LogPanel */
	public LogPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();

        logTable.setAutoCreateRowSorter(true);
        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(logTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable logTable;
    // End of variables declaration//GEN-END:variables

	public void setActionLog(ActionLogger actionLog) {
		eventList = GlazedListsSwing.swingThreadProxyList(actionLog.getEventList());

		final TableFormat<Action> tableFormat = GlazedLists.tableFormat(Action.class, propertyNames, propertyNames,
				editable);
		final EventTableModel<Action> model = new EventTableModel<Action>(eventList, tableFormat);

		logTable.setModel(model);
	}
}
